###### Appplication ########
tenant=kwt
tenant.lang=AR

spring.mail.from=Mehery SocCom<mehery.soccom@gmail.com>
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mehery.soccom@gmail.com
spring.mail.password=unhcksbuugknzefz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.defaultEncoding=UTF-8
template.TEST.title=Test Title

### SLACK #####
slack.channel.notipy.tnt=${slack.channel.notipy}
slack.channel.deployer.tnt=${slack.channel.deployer}
slack.channel.genral.tnt=${slack.channel.genral}
slack.channel.inquiry.tnt=${slack.channel.inquiry}
slack.channel.feed.tnt=${slack.channel.feed}
slack.channel.alerty.tnt=${slack.channel.alerty}
slack.channel.exception.tnt=CAJEYC47P
slack.exception.channel=CAJEYC47P

sms.channel=T
sms.request.method=FORM
sms.request.url=http://secure1.future-club.com/BulkSMSwebserviceV1/SmsService.asmx/SendSMS
sms.request.fields=Msisdn=965{mobile}&Msg={text}&Lang=l&SenderID=InfoText&UName={username}&Password={password}&AccountID=1495&TransactionID={traceid}
sms.username=xxx
sms.password=xxx
sms.secret=xxx

sms2.channel=P
sms2.request.method=FORM
sms2.request.url=http://secure1.future-club.com/BulkSMSwebserviceV1/SmsService.asmx/SendSMS
sms2.request.fields=Msisdn=965{mobile}&Msg={text}&Lang=l&SenderID=InfoText&UName={username}&Password={password}&AccountID=1495&TransactionID={traceid}
sms2.username=xxx
sms2.password=xxx
sms2.secret=xxx