###### Appplication ########
tenant=omn
tenant.lang=ar
spring.mail.from=Modern Exchange Oman<modjax.bhr@gmail.com>
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=modjax.bhr@gmail.com
spring.mail.password=ripl@1234
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.defaultEncoding=UTF-8

### SLACK #####
slack.channel.notipy.tnt=${slack.channel.notipy}
slack.channel.deployer.tnt=${slack.channel.deployer}
slack.channel.genral.tnt=${slack.channel.genral}
slack.channel.inquiry.tnt=${slack.channel.inquiry}
slack.channel.feed.tnt=${slack.channel.feed}
slack.channel.alerty.tnt=${slack.channel.alerty}
slack.channel.channel.tnt=CAHQA0AKB
slack.exception.channel=CAHQA0AKB

sms.request.method=GET
sms.request.url=https://www.ismartsms.net/iBulkSMS/HttpWS/SMSDynamicAPI.aspx
sms.request.query=UserId={username}&Password={password}&MobileNo=968{mobile}&Message={text}&Lang=0&FLashSMS=y
sms.username=mec
sms.password=xxx
sms.secret=xxx

