###### Appplication ########
tenant=bhr
tenant.lang=ar
spring.mail.from=Mehery SocCom<mehery.soccom@gmail.com>
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mehery.soccom@gmail.com
spring.mail.password=unhcksbuugknzefz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.defaultEncoding=UTF-8


### SLACK #####
slack.channel.notipy.tnt=${slack.channel.notipy}
slack.channel.deployer.tnt=${slack.channel.deployer}
slack.channel.genral.tnt=${slack.channel.genral}
slack.channel.inquiry.tnt=${slack.channel.inquiry}
slack.channel.feed.tnt=${slack.channel.feed}
slack.channel.alerty.tnt=${slack.channel.alerty}
slack.channel.exception.tnt=CAHQA0AKB
slack.exception.channel=CAHQA0AKB


sms.channel=T
sms.request.method=GET
sms.request.url=http://ems.kalaam-telecom.com/SendSms.aspx
sms.request.query=User={username}&passwd={password}&mobilenumber=973{mobile}&message={text}&sid={secret}&mtype=N&DR=Y
sms.username=mec
sms.password=xxx
sms.secret=xxx

sms2.channel=P
sms2.request.method=GET
sms2.request.url=http://ems.kalaam-telecom.com/SendSms.aspx
sms2.request.query=User={username}&passwd={password}&mobilenumber=973{mobile}&message={text}&sid={secret}&mtype=N&DR=Y
sms2.username=mec
sms2.password=xxx
sms2.secret=xxx

support.contact.subject=Inquiry
support.contact.to=onlineremit@mec.com.bh,madhuriddhi.almullagroup@gmail.com
support.contact.from=onlineremit@mec.com.bh
