#spring.main.banner-mode=off
###### App Identification  ########
app.env=LOCAL
app.group=L1
app.name=SERVER-AGENT
app.id=UIT1
app.type=AGENT
app.title=Mehery - Agent
app.message=FileUPloadLimit

###### Appplication ########
app.class=UI
app.debug=true
app.prod=false
app.swagger=true
app.audit=true
app.cache=true
app.stomp=true
app.session=true

server.port=8083
application.debug=true
application.name=Local Dev Machine
application.title=Al Mulla Exchange
app.enabled.logger=false

server.servlet.contextPath=/agent
server.contextPath=/agent

####### THYMELEAF ##############
#spring.thymeleaf.mode=LEGACYHTML5
spring.thymeleaf.cache=true
spring.thymeleaf.encoding=UTF-8

#Mehery
mry.postman.url=http://localhost:8082/postman
mry.agent.url=http://localhost:8083/agent
mry.bot.url=http://localhost:8084/bot
mry.admin.url=http://localhost:8081/admin
mry.account.url=
mry.nexus.url=http://localhost:8088/nexus
mry.chrono.url=http://localhost:8088/chrono

##POSTMAN
postman.service.url=${mry.postman.url}
postman.bot.url=${mry.bot.url}

#Tunnel
bootjx.tunnel.filter=mongo
bootjx.tunnel.cross.url=${mry.chrono.url}/tunnel

#Server Session
spring.session.store-type=redis
#spring.session.store-type=none
server.servlet.session.cookie.max-age=-1
server.servlet.session.timeout=1800
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.path=/agent
#Keeep it Default as it might have issues with RedisBased Session , as it does not seems to work with custome sessionID
#server.servlet.session.cookie.name=AGENTSESSIONID
#server.servlet.session.persistent=true
#server.servlet.session.store-dir=/tmp
#server.tomcat.basedir=/tmp
#spring.session.hazelcast.server=10.28.42.83:5701
#spring.session.hazelcast.map-name=spring:session:sessions
server.connection-timeout=-1

####### REDIS ##############
spring.redis.host=rdd1-kwt.amxremit.com
spring.redis.port=6379
spring.session.redis.namespace=spring:session_agent

##### Server Stuff ####
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto

########## Monitoring ###############
#management.security.enabled=false
#management.context-path=/monitor
#management.port=8090
#endpoints.actuator.enabled=true

#spring.boot.admin.url=http://10.28.42.36:8084

########### UI Features ###############
ui.features=BENEFICIARY,RATE_ALERT,REMIT,DASHBOARD,REFER_FRIEND
notification.range.long=500
notification.range.short=10
notification.sleep.gap=21600
notification.geo.enabled=false

########### Postman ############
fcm.senderid=770916390748

########## Fle Size limit  ########################
multipart.max-file-size=20MB
multipart.max-request-size=50MB
spring.http.multipart.max-file-size=20MB
spring.http.multipart.max-request-size=50MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

## JACKSON
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.mapper.default-view-inclusion=true

## Google
google.recaptach.site.key=6LeK33AUAAAAAJUzRyCZRV9Mtn9qU2PM-WrOk4Sm


######### Monitor ###############
#app.monitor=true
#management.security.enabled=false
#spring.boot.admin.url=http://10.28.42.36:8010


aws.s3.b2.bucket=meherydata
aws.s3.b2.accessKey=AKIAUAGH5WVJW742A6MD
aws.s3.b2.secretKey=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
aws.s3.b2.region=eu-west-2

