#spring.main.banner-mode=off
###### App Identification  ########
app.env=LOCAL
app.group=L1
app.name=SERVER-TEST
app.id=UIT1

###### Appplication ########
app.class=UI
app.debug=true
app.prod=false
app.swagger=true
app.audit=true
app.cache=true
app.stomp=true
app.session=true

server.port=8083
application.debug=true
application.name=Local Dev Machine
application.title=Al Mulla Exchange
app.enabled.logger=false

server.servlet.contextPath=/agent
server.contextPath=/agent

####### THYMELEAF ##############
#spring.thymeleaf.mode=LEGACYHTML5
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

#Mehery
mry.postman.url=http://localhost:8082/postman
mry.agent.url=http://localhost:8083/agent
mry.bot.url=http://localhost:8084/bot

##POSTMAN
postman.app.type=AGENT
postman.service.url=${mry.postman.url}
postman.bot.url=${mry.bot.url}
postman.inbound.forward.url=${mry.bot.url}/int/inbound/callback

#Server Session
server.session.cookie.max-age=-1
server.session.timeout=900
server.session.cookie.http-only=true
server.session.cookie.secure=false
server.session.cookie.path=/
#server.session.cookie.domain=local-kwt.amxremit.com
server.session.persistent=true
spring.session.store-type=none
server.session.store-dir=/tmp
server.tomcat.basedir=/tmp
#spring.session.hazelcast.server=10.28.42.83:5701
#spring.session.hazelcast.map-name=spring:session:sessions
#spring.redis.host=local-server
#spring.redis.host=local-server
spring.redis.host=rdd1-kwt.amxremit.com
spring.redis.port=6379
server.connection-timeout=-1

##### Server Stuff ####
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto

########## Monitoring ###############
#management.security.enabled=false
#management.context-path=/monitor
#management.port=8090
#endpoints.actuator.enabled=true

#spring.boot.admin.url=http://10.28.42.36:8084

########### UI Features ###############
ui.features=BENEFICIARY,RATE_ALERT,REMIT,DASHBOARD,REFER_FRIEND
notification.range.long=500
notification.range.short=10
notification.sleep.gap=21600
notification.geo.enabled=false

########### Postman ############
fcm.senderid=770916390748


## JACKSON
spring.jackson.deserialization.fail-on-unknown-properties=false

## Google
google.recaptach.site.key=6LeK33AUAAAAAJUzRyCZRV9Mtn9qU2PM-WrOk4Sm


######### Monitor ###############
#app.monitor=true
#management.security.enabled=false
#spring.boot.admin.url=http://10.28.42.36:8010


