app.default.country.id=91
app.default.currency.id=1
app.default.currency.quotename=KWD
app.default.company.id=1
app.default.branch.id=78
app.default.language.id=1

support.compliance.email=exch-compliance@almullaexchange.com


##### MongoDB ############
spring.data.mongodb.uri=mongodb://reporter:reporter@10.28.42.30:27017/reporting
spring.data.mongodb.repositories.enabled=true

#FIU
goaml.fiu.zipfile.location=/var/opt/ms-radar/upload
#goaml.fiu.zipfile.location=D:\\FIU

facebook.lane.default.type=page
facebook.lane.default.accessToken=EAAY8WTSG17kBALg61WOdfo0klUjb9yfiEK6b3nDvfYi0eEEYNu3fRJSj1xn2IsfH6hAMYXbjXbPepwNAyd8ccBJTg2QE0nckHeMR0UmRWj0tIhhnEqhDlgDJUZC0IfZAhDdVI6IDYHS8XL8KRl706i3MARfCtvhvtA2EAKZB4yS0PVNIRYKYvYTsjghldUZD
facebook.lane.default.verifyToken=A_SECRET_VERIFY_TOKEN

facebook.lane.hitech.type=page
facebook.lane.hitech.accessToken=EAAFuCCgFbJEBAAjdj7Gjnz769Wk2GhAdWNZAMbQQWJuPGcRZAM8q0XDUNVZCH96RgI7e4feNOgCXztZCBfkG7KOIAO6bQeGePBuem02EIDhG6Y23pZA6TOiNhQM75BQpLxx4bhGZBNb2OqZC3tScYg9ZAKT11jO7vojqrlgHQcZA1kWGFlsiuk6vzZAfUKg9JedwMZD
facebook.lane.hitech.verifyToken=A_SECRET_VERIFY_TOKEN