aws.s3.b1.bucket=meherydata
aws.s3.b1.accessKey=AKIAUAGH5WVJW742A6MD
aws.s3.b1.secretKey=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
aws.s3.b1.region=eu-west-2

aws.s3.b2.bucket=meherydata
aws.s3.b2.accessKey=AKIAUAGH5WVJW742A6MD
aws.s3.b2.secretKey=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
aws.s3.b2.region=eu-west-2