package com.boot.jx.postman.model;

import com.boot.jx.swagger.ApiMockModelProperty;

public class Attachment {
	@ApiMockModelProperty(example = "IMAGE", value = "Media Type", allowableValues = "IMAGE,DOCUMENT,TEXT,PDF,VIDEO")
	String mdeiaType;

	@ApiMockModelProperty(example = "12", value = "Media ID generated by MeherY")
	String mdeiaId;

	@ApiMockModelProperty(example = "https://client.mehery.com/docs/media/12.png", value = "Media ID generated by MeherY")
	String mediaURL;

	public String getMdeiaType() {
		return mdeiaType;
	}

	public void setMdeiaType(String mdeiaType) {
		this.mdeiaType = mdeiaType;
	}

	public String getMdeiaId() {
		return mdeiaId;
	}

	public void setMdeiaId(String mdeiaId) {
		this.mdeiaId = mdeiaId;
	}

	public String getMediaURL() {
		return mediaURL;
	}

	public void setMediaURL(String mediaURL) {
		this.mediaURL = mediaURL;
	}
}
