package com.boot.jx.postman.model;

import java.io.Serializable;

import com.boot.jx.swagger.ApiMockModelProperty;
import com.boot.utils.ArgUtil;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Attachment implements Serializable {
	private static final long serialVersionUID = 6420347322076291226L;

	@ApiMockModelProperty(example = "IMAGE", value = "Media Type", allowableValues = "IMAGE,DOCUMENT,TEXT,PDF,VIDEO")
	String mediaType;

	@ApiMockModelProperty(example = "12", value = "Media ID generated by Service")
	String mediaId;

	@ApiMockModelProperty(example = "https://client.mehery.com/docs/media/12.png", value = "Media URL generated by Channel")
	String mediaSrc;

	@ApiMockModelProperty(example = "https://client.mehery.com/docs/media/12.png", value = "Media URL generated by Service")
	String mediaURL;

	@ApiMockModelProperty(example = "Trransaction Receipt", value = "Media Caption")
	String mediaCaption;

	public String getMediaURL() {
		return mediaURL;
	}

	public void setMediaURL(String mediaURL) {
		this.mediaURL = mediaURL;
	}

	public Attachment mediaURL(String mediaURL) {
		this.mediaURL = mediaURL;
		return this;
	}

	public Attachment mediaId(String mediaId) {
		this.mediaId = mediaId;
		return this;
	}

	public Attachment mediaType(Object mediaTypeLocal) {
		this.mediaType = ArgUtil.parseAsString(mediaTypeLocal);
		return this;
	}

	public Attachment mediaCaption(String mediaCaption) {
		this.mediaCaption = mediaCaption;
		return this;
	}

	public Attachment mediaSrc(String mediaSrc) {
		this.mediaSrc = mediaSrc;
		return this;
	}

	public String getMediaType() {
		return mediaType;
	}

	public void setMediaType(String mediaType) {
		this.mediaType = mediaType;
	}

	public String getMediaId() {
		return mediaId;
	}

	public void setMediaId(String mediaId) {
		this.mediaId = mediaId;
	}

	public String getMediaCaption() {
		return mediaCaption;
	}

	public void setMediaCaption(String mediaCaption) {
		this.mediaCaption = mediaCaption;
	}

	public String getMediaSrc() {
		return mediaSrc;
	}

	public void setMediaSrc(String mediaSrc) {
		this.mediaSrc = mediaSrc;
	}

}
