package com.boot.jx.contak.cache;

import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.javachinna.oauth2.user.SocialEnums.ChannelPartner;
import com.javachinna.oauth2.user.SocialEnums.ChannelProvider;

@DynamoDBTable(tableName = "ProviderWebhookResponseHolder")
public class WebhookRespHolderDoc extends WebhookRespHolder {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	@DynamoDBAttribute
	public Map<String, Object> getBody() {
		return body;
	}

	@DynamoDBAttribute
	public ChannelProvider getProvider() {
		return provider;
	}

	@DynamoDBAttribute
	public ChannelPartner getPartner() {
		return partner;
	}

	@DynamoDBAttribute
	public Map<String, Object> getData() {
		return this.data;
	}

}
