##### MongoDB ############
spring.data.mongodb.uri=mongodb://localbot:localbot@10.28.42.30:27017/localbot
spring.data.mongodb.repositories.enabled=true
spring.data.mongodb.prefix=tnt

spring.ro.data.mongodb.uri=mongodb://localbot:localbot@10.28.42.30:27017/localbot
spring.ro.data.mongodb.repositories.enabled=true
spring.ro.data.mongodb.prefix=tnt

##### MongoDB for Digital ############

#spring.data.mongodb.uri=mongodb://digitaluser:RadarKaMango2021@192.168.14.243:27017/DIGITAL_AMXKWT
#spring.data.mongodb.repositories.enabled=true