#spring.main.banner-mode=off
##### ADMIN EMAILS
mry.admin.email=cherrybase786@gmail.com

###### App Identification  ########
mry.prop.logo.192=https://cdn.jsdelivr.net/gh/cherrybase/cherrybase.github.io@latest/favicon/android-chrome-192x192.png
mry.prop.website=www.cherrybase.com
mry.prop.service=CherryBase
mry.prop.reset.link=https://app.cherrybase.com/account/auth/verify-link?code=%s&account=%s