#spring.main.banner-mode=off
###### App Identification  ########
app.env=LOCAL
app.group=L1
app.name=SERVER-ACCOUNT
app.id=AD1
app.title=Account
app.type=ACCOUNT

###### Appplication ########
app.prod=false
app.swagger=true
app.session=true
app.cache=true
server.port=8086
#application.debug=true
application.name=Local Dev Machine
application.title=Account
app.enabled.logger=false

server.servlet.contextPath=/
server.contextPath=/
default.tenant.static=


###### DB mysql ########
spring.datasource.url=jdbc:mysql://10.28.42.151:3306/cbdatabase
spring.datasource.username=cbusername
spring.datasource.password=cbuserpass
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
# drop n create table, good for testing, comment this in production
#spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


#CherryBase
mry.postman.url=http://localhost:8082/postman
mry.agent.url=http://localhost:8083/agent
mry.bot.url=http://localhost:8084/bot
mry.app.url=http://app.local.com:8086
mry.account.url=
mry.superadmin.pass=mehery@1234

##POSTMAN
postman.service.url=${mry.postman.url}
postman.bot.url=${mry.bot.url}

#Server Session
server.session.cookie.max-age=-1
server.session.timeout=900
server.session.cookie.http-only=true
server.session.cookie.secure=false
#server.session.cookie.path=/admin
server.session.cookie.name=ACCTSESSIONID
#server.session.cookie.domain=local-kwt.amxremit.com
server.session.persistent=true
spring.session.store-type=none
server.session.store-dir=/tmp
server.tomcat.basedir=/tmp
#spring.session.hazelcast.server=10.28.42.83:5701
#spring.session.hazelcast.map-name=spring:session:sessions
#spring.redis.host=local-server
#spring.redis.host=local-server
spring.redis.host=rdd1-kwt.amxremit.com
spring.redis.port=6379
server.connection-timeout=-1

##### Server Stuff ####
server.tomcat.remote-ip-header=x-forwarded-for
server.tomcat.protocol-header=x-forwarded-proto

## JACKSON
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.mapper.default-view-inclusion=true

## Google
google.recaptach.site.key=6LeK33AUAAAAAJUzRyCZRV9Mtn9qU2PM-WrOk4Sm


cloudinary.name=www-mehery-com
cloudinary.api.key=866733357186819
cloudinary.api.secret=ujzGJDV-H2V6FPFJ_tW_cmwuJ2s

aws.s3.b1.bucket=meherydata
aws.s3.b1.accessKey=AKIAUAGH5WVJW742A6MD
aws.s3.b1.secretKey=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
aws.s3.b1.region=eu-west-2
