#spring.main.banner-mode=off
##### ADMIN EMAILS
mry.duperadmin.email=cherrybase786@gmail.com

mry.prop.cdn-server=https://cdn.jsdelivr.net/gh/cherrybase/cherrybase.github.io@14a08ee2f710d7274ef18ba3219f3b4e21b81860

###### App Identification  ########
mry.prop.logo.bg-x-logo-w=${mry.prop.cdn-server}/brand/bg-x-logo-w.png
mry.prop.logo.bg-x-logo-b=${mry.prop.cdn-server}/brand/bg-x-logo-b.png
mry.prop.logo.bg-x-icon-w=${mry.prop.cdn-server}/brand/bg-x-icon-w.png
mry.prop.logo.bg-x-icon=${mry.prop.cdn-server}/brand/bg-x-icon.png
mry.prop.logo.bg-w-logo-b=${mry.prop.cdn-server}/brand/bg-w-logo-b.png
mry.prop.logo.bg-w-logo=${mry.prop.cdn-server}/brand/bg-w-logo.png
mry.prop.logo.bg-b-logo-w=${mry.prop.cdn-server}/brand/bg-b-logo-w.png

mry.prop.logo.192=${mry.prop.cdn-server}/favicon/android-chrome-192x192.png
mry.prop.website=www.cherrybase.com
mry.prop.service=CherryBase
mry.prop.reset.link=https://app.cherrybase.com/account/auth/verify-link?code=%s&account=%s