#spring.main.banner-mode=off
###### App Identification  ########
app.env=Demo
app.group=1
app.name=SERVER-XMS
app.id=XMS1

###### Appplication ########
app.class=UI
app.debug=true
app.prod=false
app.swagger=true
app.audit=false
app.cache=false
app.stomp=false
app.session=true

server.port=8080
application.debug=true
application.name=Local Dev Machine
application.title=Cross-Channel Messaging Service
app.enabled.logger=false

server.servlet.contextPath=/xms
server.contextPath=/xms

####### THYMELEAF ##############
#spring.thymeleaf.mode=LEGACYHTML5
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

swagger.package=com.boot.jx.xms
swagger.key.enabled=false
swagger.tenant.enabled=false
swagger.trace.enabled=false
swagger.tranx.enabled=false

