#spring.main.banner-mode=off
###### App Identification  ########
app.env=LOCAL
app.group=1
app.name=SERVER-XMS
app.id=XMS1
app.type=XMS

###### Appplication ########
app.class=UI
app.debug=false
app.prod=false
app.swagger=true
app.audit=false
app.cache=true
app.stomp=false

server.port=8085
application.debug=true
application.name=Local Dev Machine
application.title=Cross-Channel Messaging Service
app.enabled.logger=false

server.servlet.contextPath=/xms
server.contextPath=/xms

####### THYMELEAF ##############
#spring.thymeleaf.mode=LEGACYHTML5
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

## JACKSON
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.mapper.default-view-inclusion=true

#######  CherryBase ###########
mry.postman.url=http://localhost:8082/postman
mry.agent.url=http://localhost:8083/agent
mry.admin.url=http://localhost:8084/admin
mry.bot.url=http://localhost:8084/bot
mry.account.url=

#######  POSTMAN ###########
postman.service.url=${mry.postman.url}
postman.bot.url=${mry.bot.url}


##### Storage ######
cloudinary.name=www-mehery-com
cloudinary.api.key=866733357186819
cloudinary.api.secret=ujzGJDV-H2V6FPFJ_tW_cmwuJ2s

aws.s3.b1.bucket=meherydata
aws.s3.b1.accessKey=AKIAUAGH5WVJW742A6MD
aws.s3.b1.secretKey=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
aws.s3.b1.region=eu-west-2


#######  SWAGGER ###########
swagger.package=com.boot.jx.xms
swagger.key.enabled=false
swagger.tenant.enabled=false
swagger.trace.enabled=false
swagger.tranx.enabled=false
swagger.contact.url=
swagger.contact.name=
swagger.contact.email=
swagger.title=Messaging APIs
swagger.description=\
	All the requests are required to be authorized using an API Key authentication. \
	\n Adding *x-api-key* in the header with your unique API Key as a value will grant access.\
	\n To get your *x-api-key* [visit documentation](/server-xms/)
spring.profiles.include=docs

