swagger.InboundWebhooks.description=\
	Webhooks can be used for:\
		* Inbound Message Notifications: Use it to get a notification you when you have received a message.\
		* Message Status Notifications: Monitor the status of sent messages.
swagger.InboundWebhooks.onMessageCallback.description=\
	Inbound Message Notifications: Use it to get a notification when you have received a message.
swagger.InboundWebhooks.onProfileCallback.description=\
	Contact Information : Use to respond with contact information for incoming message
swagger.InboundWebhooks.onActionCallback.description=\
	Action Callback :  Use it to get a notification when agent clicks on any action in AgentPanel
swagger.OutboundApiV1.sendMessage.description=\
	Use the message API to send text messages, media, documents, and message templates to your customers\n\
	You can send messages by making a POST call regardless of message type. The content of the JSON message body differs for each type of message (text, image, etc.).
swagger.ConfigApiV1.setWebhookUrl.description=\
	You must configure a callback (Webhook URL) to receive messages.\n\
	To deploy a live webhook that can receive webhook events, your code must have the following\
		* HTTPS support\
 		* A valid SSL certificate
swagger.ConfigApiV1.getChannels.description=List of all the configured channels\
	Pass sandbox=true if you want sandbox channels also to be part of list
swagger.SessionApiV1.getSessionMessages.description=use this api to fetch list of all messages for sessionId.\n\
	you can get _sessionId_ from inbound message body
swagger.SessionApiV1.sessionRouting.description=Assign session to different queue, all the future inbound messages will be sent to this queue	