package com.boot.jx.postman.model;

import java.io.Serializable;

import org.apache.commons.io.FilenameUtils;

import com.boot.jx.model.CommonFile;
import com.boot.jx.postman.PMConstants.DEFAULT_VALUES;
import com.boot.jx.swagger.ApiMockModelProperty;
import com.boot.utils.ArgUtil;
import com.boot.utils.Constants;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Attachment implements Serializable {
	private static final long serialVersionUID = 6420347322076291226L;

	@ApiMockModelProperty(example = "23m234233232323", value = "Unique Attachment Id")
	String attachmentId;

	@ApiMockModelProperty(example = "IMAGE", value = "Media Type",
			allowableValues = "IMAGE,DOCUMENT,TEXT,PDF,VIDEO,URL,AUDIO")
	String mediaType;

	@ApiMockModelProperty(example = "IMAGE", value = "Media SubType Type",
			allowableValues = "STORY_MENTION,SHARE,bg_voice etc")
	String mediaSubType;

	@ApiMockModelProperty(example = "image/png", value = "Mime Type")
	String mediaMimeType;

	@ApiMockModelProperty(example = "23m234233232323", value = "Media ID generated by Service")
	protected String mediaId;

	@ApiMockModelProperty(example = "23m234233232323ext", value = "Media ID generated by Channel")
	String mediaIdExt;

	@ApiMockModelProperty(example = "23m234233232323inline",
			value = "Media ID used by Message for inline/part of body content")
	String mediaIdInline;

	@ApiMockModelProperty(example = "https://client.service.com/docs/media/12.png",
			value = "Media URL generated by Channel")
	String mediaSrc;

	@ApiMockModelProperty(example = "https://client.service.com/docs/media/12.png",
			value = "Media URL generated by Service")
	String mediaURL;

	@ApiMockModelProperty(example = "Hi <b>John</b>, this is your <i>image</i>", value = "Media Template")
	String mediaTemplate;

	@ApiMockModelProperty(example = DEFAULT_VALUES.MEDIA_TEMPLATE_STYLE, value = "Media Template Wrapper")
	String mediaTemplateStyle;

	@ApiMockModelProperty(example = "Transaction Receipt", value = "Media Caption")
	String mediaCaption;

	@ApiMockModelProperty(example = "TransactionReceipt.pdf", value = "File Name")
	String mediaName;

	@ApiMockModelProperty(example = "ABC_PROMO", value = "QuickMedia Code")
	String mediaCode;

	public String getMediaURL() {
		return mediaURL;
	}

	public void setMediaURL(String mediaURL) {
		this.mediaURL = mediaURL;
	}

	public Attachment mediaURL(String mediaURL) {
		this.mediaURL = mediaURL;
		if (!ArgUtil.is(this.mediaName)) {
			this.mediaName = FilenameUtils.getName(mediaURL);
		}
		return this;
	}

	public Attachment mediaId(String mediaId) {
		this.mediaId = mediaId;
		return this;
	}

	public Attachment mediaIdExt(String mediaIdExt) {
		this.mediaIdExt = mediaIdExt;
		return this;
	}

	public Attachment mediaIdInline(String mediaIdInline) {
		this.mediaIdInline = mediaIdInline;
		return this;
	}

	public Attachment mediaType(Object mediaTypeLocal) {
		this.mediaType = ArgUtil.parseAsString(mediaTypeLocal);
		return this;
	}

	public Attachment mediaSubType(Object mediaSubType) {
		this.mediaSubType = ArgUtil.parseAsString(mediaSubType, Constants.BLANK).toUpperCase();
		return this;
	}

	public Attachment mediaMimeType(Object mediaMimeTypeLocal) {
		this.mediaMimeType = ArgUtil.parseAsString(mediaMimeTypeLocal);
		return this;
	}

	public Attachment mediaCaption(String mediaCaption) {
		this.mediaCaption = mediaCaption;
		return this;
	}

	public Attachment mediaSrc(String mediaSrc) {
		this.mediaSrc = mediaSrc;
		return this;
	}

	public Attachment mediaName(String mediaName) {
		this.mediaName = mediaName;
		return this;
	}

	public String getMediaType() {
		if (!ArgUtil.is(this.mediaType) && ArgUtil.is(this.mediaURL)) {
			this.mediaType = ArgUtil.parseAsString(new CommonFile().url(this.mediaURL).getFileType());
		}
		return this.mediaType;
	}

	public void setMediaType(String mediaType) {
		this.mediaType = mediaType;
	}

	public String getMediaId() {
		return mediaId;
	}

	public void setMediaId(String mediaId) {
		this.mediaId = mediaId;
	}

	public String getMediaCaption() {
		return mediaCaption;
	}

	public void setMediaCaption(String mediaCaption) {
		this.mediaCaption = mediaCaption;
	}

	public String getMediaSrc() {
		return mediaSrc;
	}

	public void setMediaSrc(String mediaSrc) {
		this.mediaSrc = mediaSrc;
	}

	public String getMediaName() {
		return mediaName;
	}

	public void setMediaName(String mediaName) {
		this.mediaName = mediaName;
	}

	public String getMediaMimeType() {
		return mediaMimeType;
	}

	public void setMediaMimeType(String mediaMimeType) {
		this.mediaMimeType = mediaMimeType;
	}

	public String getMediaSubType() {
		return mediaSubType;
	}

	public void setMediaSubType(String mediaSubType) {
		this.mediaSubType = mediaSubType;
	}

	public String getMediaCode() {
		return mediaCode;
	}

	public void setMediaCode(String mediaCode) {
		this.mediaCode = mediaCode;
	}

	public String getMediaTemplate() {
		return mediaTemplate;
	}

	public void setMediaTemplate(String mediaTemplate) {
		this.mediaTemplate = mediaTemplate;
	}

	public String getAttachmentId() {
		return attachmentId;
	}

	public void setAttachmentId(String id) {
		this.attachmentId = id;
	}

	public String getMediaTemplateStyle() {
		return mediaTemplateStyle;
	}

	public void setMediaTemplateStyle(String mediaTemplateStyle) {
		this.mediaTemplateStyle = mediaTemplateStyle;
	}

	public String getMediaIdExt() {
		return mediaIdExt;
	}

	public void setMediaIdExt(String mediaIdExt) {
		this.mediaIdExt = mediaIdExt;
	}

	public String getMediaIdInline() {
		return mediaIdInline;
	}

	public void setMediaIdInline(String mediaIdInline) {
		this.mediaIdInline = mediaIdInline;
	}

}
