mry.postman.url=http://localhost:8082/postman
mry.agent.url=http://localhost:8083/agent
mry.bot.url=http://localhost:8084/bot

mry.cdn.url=https://cdn.jsdelivr.net/gh/cherrybase/cherrybase.github.io@gh-pages
mry.superadmin.user=superadmin
mry.superadmin.pass=cherry@1234

mry.app.login.secret=Ulb0bBpAQPd10gENuOz1m6LlO7kubPfw
mry.app.login.key=2pUUQ9e8t4

common.const.app=app
