#spring.main.banner-mode=off
mry.prop.cdn-server=https://cdn.jsdelivr.net/gh/cherrybase/cherrybase.github.io@a19c367e3438cfa0cb9608ef5701b6b488c19790

###### App Identification  ########
mry.prop.logo.bg-x-logo-w=${mry.prop.cdn-server}/brand/bg-x-logo-w.png
mry.prop.logo.bg-x-logo-b=${mry.prop.cdn-server}/brand/bg-x-logo-b.png
mry.prop.logo.bg-x-logo=${mry.prop.cdn-server}/brand/bg-x-logo.png
mry.prop.logo.bg-x-icon-w=${mry.prop.cdn-server}/brand/bg-x-icon-w.png
mry.prop.logo.bg-x-icon=${mry.prop.cdn-server}/brand/bg-x-icon.png
mry.prop.logo.bg-w-logo-b=${mry.prop.cdn-server}/brand/bg-w-logo-b.png
mry.prop.logo.bg-w-logo=${mry.prop.cdn-server}/brand/bg-w-logo.png
mry.prop.logo.bg-b-logo-w=${mry.prop.cdn-server}/brand/bg-b-logo-w.png

mry.prop.service.name=CherryBase
mry.prop.service.server=${branch.service.domain}
mry.prop.service.domain=cherrybase.com
mry.prop.service.website=www.${mry.prop.service.domain}
mry.prop.service.website.link=https://${mry.prop.service.website}
mry.prop.service.aboutus.link=${mry.prop.service.website.link}/#aboutus
mry.prop.service.privacy.link=${mry.prop.service.website.link}/privacy-policy/#page-content
mry.prop.service.tos.link=${mry.prop.service.website.link}/terms-conditions/#page-content
mry.prop.service.docs.link=${mry.prop.service.website.link}/docs
mry.prop.service.docs.api.link=${mry.prop.service.website.link}/docs/api
mry.prop.service.docs.chat.link=${mry.prop.service.website.link}/docs/chat
mry.prop.service.blog.link=${mry.prop.service.website.link}/blog

mry.prop.service.aboutus.md=${mry.prop.cdn-server}/aboutus.md
mry.prop.service.privacy.md=${mry.prop.cdn-server}/privacy.md
mry.prop.service.tos.md=${mry.prop.cdn-server}/tos.md

#Social
mry.prop.social.email=contact@cherrybase.com
mry.prop.social.twitter=cherrybase
mry.prop.social.facebook=cherrybase
mry.prop.social.instagram=cherrybase
mry.prop.social.github=
mry.prop.social.telegram=cherrybot
mry.prop.social.whatsapp=998877665544


mry.prop.logo.192=${mry.prop.cdn-server}/favicon/android-chrome-192x192.png
mry.prop.website=www.cherrybase.com
mry.prop.reset.link=https://app.cherrybase.com/partner/auth/verify-link?code=%s&account=%s


# Others
mry.prop.sales.email=sales@mehery.com