app.venv=${branch.service.domain}

mry.postman.url=http://localhost:8082/postman
mry.agent.url=http://localhost:8083/agent
mry.bot.url=http://localhost:8084/bot
mry.account.url=http://localhost:8086/
mry.scriptus.url=http://nodebot.mehery.io:8085
mry.scriptus.secret=xlJVFxiB9Tb76ioxrmorsvlkV8h8aELc

mry.proxy.enabled=false
mry.cdn.url=https://cdn.jsdelivr.net/gh/cherrybase/cherrybase.github.io@gh-pages
mry.superadmin.user=superadmin
mry.superadmin.pass=cherry@1234
mry.duperadmin.email=cherrybase786@gmail.com

mry.app.login.secret=Ulb0bBpAQPd10gENuOz1m6LlO7kubPfw
mry.app.login.key=2pUUQ9e8t4

common.const.app=app
mry.domain.active=true
mry.domain.xms.active=true
mry.domain.agent.active=true