postman.telegram.default.lane=meherybot

postman.telegram.lane.meherybot.type=bot
postman.telegram.lane.meherybot.accessToken=1562072430:AAGfXWspMQHSwotoxYv1cQr7XaGR6r2SrB8
postman.telegram.webhook.url=
postman.telegram.webhook.path=/ext/inbound/tg/callback
