gupshup.wa.number=96555259800
gupshup.api.url=https://media.smsgupshup.com
gupshup.notify.id=2000193425
gupshup.notify.pass=b24FQcHr
gupshup.chat.id=2000193428
gupshup.chat.pass=J9hUdTFa
gupshup.agent.url=https://demo.gsagents.com