postman.twitter.default.lane=mehery_soccom
postman.twitter.polling.lanes=
postman.twitter.webhook.lanes=
postman.twitter.webhook.url=
postman.twitter.webhook.path=/ext/inbound/tw/callback

postman.twitter.lane.mehery_soccom.type=page
postman.twitter.lane.mehery_soccom.env_name=demo
postman.twitter.lane.mehery_soccom.consumer-key=gj9xDe4LPUBkrSW5Oaq1KHICY
postman.twitter.lane.mehery_soccom.consumer-secret=2ZVDKIfWR3QS2mYEpSgtuxNPaTFgSRYzetCzYXyazxwmhhMhZd
postman.twitter.lane.mehery_soccom.access-token=1347549234095013889-0XAUcfNsfOcFB0qXqbm6peFeDnAAF5
postman.twitter.lane.mehery_soccom.access-token-secret=PHChv32mrEBxMBhNRvl482HTMqMopvqkY6F2w8Btk48lL


postman.twitter.lane.rabiluddin.type=page
postman.twitter.lane.rabiluddin.consumer-key=Ju7Udz3pFVACjiHsptTLNGcNe
postman.twitter.lane.rabiluddin.consumer-secret=v4JAF7ijiv78QDZJUsO9TjzZnC8p74CeX7x46NSElBul10iW29
postman.twitter.lane.rabiluddin.access-token=131138374-pf8HViS423yZMjFE638STbjcWZZFHVRdg6zugGhc
postman.twitter.lane.rabiluddin.access-token-secret=cOBv28OguMIxEIyFW0Ykf2b0mxd8bYBCRyIvp4REfovqh

