gupshup.wa.number=919289221771
gupshup.api.url=https://media.smsgupshup.com
gupshup.notify.id=2000196167
gupshup.notify.pass=bB!SMZza
gupshup.chat.id=2000196168
gupshup.chat.pass=DHU*$Xps
gupshup.agent.url=https://demo.gsagents.com