facebook.lane.default.type=page
facebook.lane.default.accessToken=EAAY8WTSG17kBALg61WOdfo0klUjb9yfiEK6b3nDvfYi0eEEYNu3fRJSj1xn2IsfH6hAMYXbjXbPepwNAyd8ccBJTg2QE0nckHeMR0UmRWj0tIhhnEqhDlgDJUZC0IfZAhDdVI6IDYHS8XL8KRl706i3MARfCtvhvtA2EAKZB4yS0PVNIRYKYvYTsjghldUZD
facebook.lane.default.verifyToken=A_SECRET_VERIFY_TOKEN
facebook.lane.default.appSecret=7d1782a8fa2fc78db4ceae9c545b6fc3

facebook.lane.181412048587363.type=page
facebook.lane.181412048587363.accessToken=EAAFuCCgFbJEBAAFESQd5zHhnPi5s8ZAj49HBdxQH8ZC9G0AYJTyUMdvsQbZAUkafwIIutjkiYVSA72GMZCNplhDV5fVZASWfyXZBCsZAx8bdYwMT0OnyQBLTWXWyh5HtSKZCO75OzaqYcDyDPMXZBTNpXwDpgisPxQaisfwxA8W2HZC1puD9dOJqTEJBlfZAc7tClUZD
facebook.lane.181412048587363.verifyToken=A_SECRET_VERIFY_TOKEN
facebook.lane.181412048587363.appSecret=7d1782a8fa2fc78db4ceae9c545b6fc3

facebook.lane.101842438530284.type=page
facebook.lane.101842438530284.accessToken=EAACO0T1nsdsBAGjZCOc8ZB77pwZBNTZANbl76suMzVowJuRle89WembzlTWFozB4ADrUWZCBTVE2uRIZBZC0ZBRj4CJuS8SvHp347zSbIX9ZCsnhcBgL9c0jgjtBApAe8FKkEllnTQvcZBMLtwkuV9hSkbeAKzuJiZCzXwCeAf3mrk2FZCZCWPt3yptEolvPo9VaW6zQZD
facebook.lane.101842438530284.verifyToken=A_SECRET_VERIFY_TOKEN
facebook.lane.101842438530284.appSecret=f721908b89ced5f7c63364ce93b522bf

facebook.lane.375143382517674.type=page
facebook.lane.375143382517674.accessToken=EAAG15wYDNcwBAI4Cz8BCKPA1jvYtSEGJ5yneJxldEpThHqtyrvHgD8wTJ2PjCh8wSNuKp6mZBLhmAlFKTANiRCOtGtB9iWmnlR4t9lqqEV9ZBlRfiKn2N4ppf9pvchfczAW4RzJUdZA5Ih2ZAU4vUU6fUc9f9GZA8b1SFRZApyEAZDZD
facebook.lane.375143382517674.verifyToken=A_SECRET_VERIFY_TOKEN
facebook.lane.375143382517674.appSecret=17ae8379c6ee07e1d75d6b3df684f12b