facebook.lane.default.type=page
facebook.lane.default.accessToken=EAAY8WTSG17kBALg61WOdfo0klUjb9yfiEK6b3nDvfYi0eEEYNu3fRJSj1xn2IsfH6hAMYXbjXbPepwNAyd8ccBJTg2QE0nckHeMR0UmRWj0tIhhnEqhDlgDJUZC0IfZAhDdVI6IDYHS8XL8KRl706i3MARfCtvhvtA2EAKZB4yS0PVNIRYKYvYTsjghldUZD
facebook.lane.default.verifyToken=A_SECRET_VERIFY_TOKEN

facebook.lane.hitech.type=page
facebook.lane.hitech.accessToken=EAAFuCCgFbJEBAAjdj7Gjnz769Wk2GhAdWNZAMbQQWJuPGcRZAM8q0XDUNVZCH96RgI7e4feNOgCXztZCBfkG7KOIAO6bQeGePBuem02EIDhG6Y23pZA6TOiNhQM75BQpLxx4bhGZBNb2OqZC3tScYg9ZAKT11jO7vojqrlgHQcZA1kWGFlsiuk6vzZAfUKg9JedwMZD
facebook.lane.hitech.verifyToken=A_SECRET_VERIFY_TOKEN