postman.app.type=OTHER
postman.service.url=http://127.0.0.1:8082/postman
postman.agent.url=
postman.bot.url=
postman.inbound.forward.url=
postman.chat.dummy.user.enabled=false
postman.chat.dummy.bot.enabled=false
postman.chat.session.timeout=5min
postman.chat.client.key=RANDOM
app.tmpl.local=false

app.test.email=
app.test.mobile=
app.test.whatsapp=