
twitter.lane.default.type=page
twitter.lane.default.verifyToken=A_SECRET_VERIFY_TOKEN

twitter4j.debug=true
twitter4j.oauth.consumer-key=Ju7Udz3pFVACjiHsptTLNGcNe
twitter4j.oauth.consumer-secret=v4JAF7ijiv78QDZJUsO9TjzZnC8p74CeX7x46NSElBul10iW29
twitter4j.oauth.access-token=131138374-pf8HViS423yZMjFE638STbjcWZZFHVRdg6zugGhc
twitter4j.oauth.access-token-secret=cOBv28OguMIxEIyFW0Ykf2b0mxd8bYBCRyIvp4REfovqh

